<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="IBM-JQCV2F3" failures="1" tests="4" name="Default test" time="95.244" errors="0" timestamp="2023-04-20T22:22:47 IST">
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="12.468"/>
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="29.573"/>
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="32.015"/>
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="20.831">
    <failure type="java.lang.AssertionError" message="expected [Address saved] but found [You have submitted an address that is already in your address book]">
      <![CDATA[java.lang.AssertionError: expected [Address saved] but found [You have submitted an address that is already in your address book]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at StepDefinations.addressAddTest.check_if_address_is_sucessfully_saved(addressAddTest.java:39)
at âœ½.Check if address is sucessfully saved(file:///C:/Users/003VR5744/eclipse-workspace/E2EFramework/src/test/java/features/Amazon.feature:30)
]]>
    </failure>
  </testcase> <!-- runScenario -->
</testsuite> <!-- Default test -->
