<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="IBM-JQCV2F3" failures="1" tests="4" name="Test" time="131.089" errors="0" timestamp="2023-04-27T17:22:26 IST">
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="20.112"/>
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="41.406"/>
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="39.311"/>
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="29.351">
    <failure type="java.lang.AssertionError" message="expected [Address saved] but found [You have submitted an address that is already in your address book]">
      <![CDATA[java.lang.AssertionError: expected [Address saved] but found [You have submitted an address that is already in your address book]
at StepDefinations.addressAddTest.check_if_address_is_sucessfully_saved(addressAddTest.java:39)
at âœ½.Check if address is sucessfully saved(file:///C:/Users/003VR5744/eclipse-workspace/E2EFramework/src/test/java/features/Amazon.feature:30)
... Removed 6 stack frames]]>
    </failure>
  </testcase> <!-- runScenario -->
</testsuite> <!-- Test -->
